# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 244d72b94a370888a6f159537c3a55d5d2ad98b9ea2cb6b9860c56e1ab3f43d4f92fb76f57d28e1e901d74def67c0d9851220163433b9fe85cb83555e84bc4f4

test:
  secret_key_base: 1b4002eb4b80279d7cf9a24c45b5a29a1453b9cfd92ed107897ea2d966ed96c0f604228528da3e7c5d1b6108a948a0702c3048a38c61e65fa1aab5eb32d592a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
